name: Sync labels
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
            MCRE-BE/pyRobocopy
            MCRE-BE/py-file-attributes
            MCRE-BE/ntfy_lite
            MCRE-BE/PyParquetViewer
          token: ${{ secrets.PERSONAL_TOKEN }}
